Volleyball\Bundle\OrganizationBundle\Entity\Council:
    type: entity
    table: council
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        description:
            type: string
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        slug:
            type: string
            gedmo:
                slug:
                    fields:
                        - name
    ManyToOne:
        organization:
            targetEntity: Volleyball\Bundle\OrganizationBundle\Entity\Organization
            inversedBy: council
            joinColumn:
                name: organization_id
                referencedColumnName: id
    OneToMany:
        regions:
            targetEntity: Volleyball\Bundle\OrganizationBundle\Entity\Region
            mappedBy: council